---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
      time: "08:00"
      timezone: "Europe/London"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "monthly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
